// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWiELeqP6uYcJcjwj5xhXWPegRSd5jrGw',
    appId: '1:632525194948:web:37d12b505c1b00f0db6b91',
    messagingSenderId: '632525194948',
    projectId: 'medical-herbs-app',
    authDomain: 'medical-herbs-app.firebaseapp.com',
    storageBucket: 'medical-herbs-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4V6EO62VZzrJzpxLx7qDzlFnY3lMjPyc',
    appId: '1:632525194948:android:ecf0510de8fafa4fdb6b91',
    messagingSenderId: '632525194948',
    projectId: 'medical-herbs-app',
    storageBucket: 'medical-herbs-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGM7vsH-hRtVEHDuy7tpB9tu6-NfnNMZs',
    appId: '1:632525194948:ios:59771c3d45dc0d2adb6b91',
    messagingSenderId: '632525194948',
    projectId: 'medical-herbs-app',
    storageBucket: 'medical-herbs-app.firebasestorage.app',
    iosBundleId: 'com.example.herbsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGM7vsH-hRtVEHDuy7tpB9tu6-NfnNMZs',
    appId: '1:632525194948:ios:59771c3d45dc0d2adb6b91',
    messagingSenderId: '632525194948',
    projectId: 'medical-herbs-app',
    storageBucket: 'medical-herbs-app.firebasestorage.app',
    iosBundleId: 'com.example.herbsFlutter',
  );
}
